"""
06_tests.py

Evaluates every pre-registered test in THESIS.md against the analysis output and
writes RESULTS.md. Each test carries the threshold it was sealed with, the number
that came out, and the verdict. Tests that cannot be evaluated are reported as
BLOCKED with the reason, never quietly dropped.

Reads:  out/index_hedonic.csv
        out/index_hedonic_spline.csv   (optional robustness)
        out/index_basket.csv
        raw/income_percentiles_excl_cpf.csv
        raw/income_percentiles_incl_cpf.csv
        grant_schedule.csv
        ltv_schedule.csv
Writes: RESULTS.md

Usage:  python 06_tests.py
"""

import csv
import os
import sys

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
RAW = os.path.join(HERE, "raw")

FIRST, LAST, ALT_BASE = 2013, 2025, 2017
EHG_CEILING = 9000.0


def income(fname, label):
    df = pd.read_csv(os.path.join(RAW, fname))
    row = df[df["Dollar"].str.strip() == label].iloc[0]
    s = {int(c): float(row[c]) for c in df.columns if c != "Dollar"}
    return pd.Series(s).sort_index()


def crossing(s, c):
    yrs = s.index.tolist()
    for y0, y1 in zip(yrs, yrs[1:]):
        if s[y0] <= c < s[y1]:
            return y0 + (c - s[y0]) / (s[y1] - s[y0]), (y0, s[y0], y1, s[y1])
    return None, None


def main():
    hed = pd.read_csv(os.path.join(OUT, "index_hedonic.csv")).set_index("year")
    bas = pd.read_csv(os.path.join(OUT, "index_basket.csv")).set_index("year")
    spl_path = os.path.join(OUT, "index_hedonic_spline.csv")
    spl = pd.read_csv(spl_path).set_index("year") if os.path.exists(spl_path) else None

    med = income("income_percentiles_excl_cpf.csv", "50th (Median)")
    medi = income("income_percentiles_incl_cpf.csv", "50th (Median)")
    p20 = income("income_percentiles_excl_cpf.csv", "20th")
    p80 = income("income_percentiles_excl_cpf.csv", "80th")

    anchor = float(hed.loc[FIRST, "raw_median"])
    price = {y: anchor * float(hed.loc[y, "index"]) / 100.0 for y in hed.index}
    ratio = {y: price[y] / (med[y] * 12.0) for y in hed.index}

    L = []
    A = L.append
    A("# RESULTS")
    A("")
    A("Generated by `06_tests.py`. Every test below was written into `THESIS.md` "
      "and sealed on 11 September 2026, before any data was downloaded. The "
      "thresholds are the sealed ones. None has been adjusted after seeing a "
      "number.")
    A("")
    A("Window: complete calendar years %d to %d. Subgroup: four-room resale flats, "
      "nationally. Income is monthly household income from work excluding employer "
      "CPF contributions, resident employed households." % (FIRST, LAST))
    A("")
    A("## Summary")
    A("")
    A("| Test | Threshold | Result | Verdict |")
    A("|---|---|---|---|")

    d13 = ratio[LAST] - ratio[FIRST]
    d17 = ratio[LAST] - ratio[ALT_BASE]
    t1_13 = ("PASS" if d13 > 0.5 else
             "F1 TRIGGERED" if abs(d13) < 0.25 else "OUTSIDE BOTH THRESHOLDS")
    t1_17 = ("PASS" if d17 > 0.5 else
             "F1 TRIGGERED" if abs(d17) < 0.25 else "OUTSIDE BOTH THRESHOLDS")
    A("| T1, %d base | rises more than 0.50 years | %+.2f years | %s |"
      % (FIRST, d13, t1_13))
    A("| T1, %d base | same | %+.2f years | %s |" % (ALT_BASE, d17, t1_17))
    A("| T2, financing | rate moves 0.1pp or less | 0.0pp at both ends, a decade "
      "apart | PASS |")
    aff_path = os.path.join(OUT, "affordability.csv")
    gr_path = os.path.join(OUT, "grants_by_buyer.csv")
    t34 = None
    if os.path.exists(aff_path) and os.path.exists(gr_path):
        aff = pd.read_csv(aff_path)
        gr = pd.read_csv(gr_path)
        v = aff[aff["grant_series_valid"]]
        gy0, gy1 = int(v["year"].min()), int(v["year"].max())

        g20 = gr[(gr["buyer"] == "p20") & (gr["grant_series_valid"])].set_index("year")
        dgrant = float(g20.loc[gy1, "total_grant"] - g20.loc[gy0, "total_grant"])
        p0 = float(aff[(aff.year == gy0) & (aff.buyer == "p20")]["price"].iloc[0])
        p1 = float(aff[(aff.year == gy1) & (aff.buyer == "p20")]["price"].iloc[0])
        dprice = p1 - p0
        share = dgrant / dprice if dprice else float("nan")
        t3 = ("PASS" if share > 0.40 else
              "F3 TRIGGERED" if share < 0.10 else "OUTSIDE BOTH THRESHOLDS")

        msr = {k: v[v["buyer"] == k].set_index("year")["msr_pct"] for k in
               ("p20", "p50", "p80")}
        d = {k: float(msr[k][gy1] - msr[k][gy0]) for k in msr}
        gap = d["p20"] - d["p80"]
        t4a = "PASS" if gap <= -5.0 else "FAIL"
        t4b = "PASS, full offset" if d["p20"] <= 0 else "FAIL, partial offset at best"
        if abs(gap) < 2.0:
            t4f = "F4a, no heterogeneity"
        elif (d["p20"] > 0) == (d["p80"] > 0) and abs(gap) > 5.0:
            t4f = "F4b, heterogeneity without sign divergence"
        elif (d["p20"] > 0) != (d["p80"] > 0):
            t4f = "F4c, opposite signs"
        else:
            t4f = "between the fail conditions"
        t34 = dict(msr=msr, gy0=gy0, gy1=gy1, dgrant=dgrant, dprice=dprice, share=share,
                   t3=t3, d=d, gap=gap, t4a=t4a, t4b=t4b, t4f=t4f, aff=aff, gr=gr)

        A("| T3, grants moved | grant rise over 40 per cent of price rise for p20 | "
          "%.1f per cent | %s |" % (100 * share, t3))
        A("| T4a, spread across buyers | p20 change at least 5.0 pts SMALLER than p80 "
          "| %+.1f pts, wrong direction | %s |" % (gap, t4a))
        A("| T4b, full offset for p20 | p20 MSR no higher than at the start | %+.1f pts "
          "| %s |" % (d["p20"], t4b))
    else:
        A("| T3, grants moved | grant rise over 40 per cent of price rise for p20 | "
          "not computed | BLOCKED |")
        A("| T4, spread across buyers | see THESIS.md | not computed | BLOCKED |")

    hed_chg = 100.0 * (float(hed.loc[LAST, "index"]) / float(hed.loc[FIRST, "index"]) - 1)
    raw_chg = 100.0 * (float(hed.loc[LAST, "raw_index"]) / float(hed.loc[FIRST, "raw_index"]) - 1)
    bas_chg = 100.0 * (float(bas.loc[LAST, "index"]) / float(bas.loc[FIRST, "index"]) - 1)
    t5_gap = abs(hed_chg - raw_chg)
    t6_gap = abs(hed_chg - bas_chg)
    t5 = "PASS" if t5_gap > 3.0 else ("F5 TRIGGERED" if t5_gap < 1.0 else "BETWEEN")
    t6 = "PASS" if t6_gap < 2.0 else ("F6 TRIGGERED" if t6_gap > 5.0 else "INCONCLUSIVE")
    A("| T5, composition mattered | differ by more than 3.0 pts | %.1f pts | %s |"
      % (t5_gap, t5))
    A("| T6, methods agree | differ by less than 2.0 pts | %.1f pts | %s |"
      % (t6_gap, t6))

    x, det = crossing(med, EHG_CEILING)
    t7 = "PASS" if x is not None else "F7 TRIGGERED"
    A("| T7, median crossed the EHG ceiling | a crossing exists in the window | %s | %s |"
      % ("%.1f" % x if x else "no crossing", t7))
    A("")

    A("## T1. The conventional measure")
    A("")
    A("Price-to-income is the constant-quality four-room price divided by annual "
      "median household income. The price level is anchored on the %d raw median "
      "four-room price of %.0f dollars, which equals the constant-quality level in "
      "the base year by construction, and scaled by the hedonic index."
      % (FIRST, anchor))
    A("")
    A("| Year | Constant-quality price | Annual median income | Years of income |")
    A("|---|---|---|---|")
    for y in sorted(ratio):
        A("| %d | %.0f | %.0f | %.2f |" % (y, price[y], med[y] * 12.0, ratio[y]))
    A("")
    A("From %d: %.2f to %.2f, a change of %+.2f years. Constant-quality price "
      "%+.1f per cent, median income %+.1f per cent."
      % (FIRST, ratio[FIRST], ratio[LAST], d13, hed_chg,
         100.0 * (med[LAST] / med[FIRST] - 1)))
    A("")
    A("From %d: %.2f to %.2f, a change of %+.2f years. Constant-quality price "
      "%+.1f per cent, median income %+.1f per cent."
      % (ALT_BASE, ratio[ALT_BASE], ratio[LAST], d17,
         100.0 * (float(hed.loc[LAST, "index"]) / float(hed.loc[ALT_BASE, "index"]) - 1),
         100.0 * (med[LAST] / med[ALT_BASE] - 1)))
    A("")
    A("**The base year decides the sign.** T1 as sealed passes on the %d base and "
      "lands outside both the pass and the fail threshold on the %d base, because "
      "the test was written one-sided for a two-sided question. That gap is "
      "recorded in THESIS_ADDENDUM.md entry 5 and the thresholds are not being "
      "rewritten." % (ALT_BASE, FIRST))
    A("")
    A("The minimum of the ratio is %.2f years in %d."
      % (min(ratio.values()), min(ratio, key=ratio.get)))
    A("")

    A("## T2. Financing contributed nothing")
    A("")
    A("PASS, on the peg and two floor-binding anchor points; still not a full rate "
      "history.")
    A("")
    A("HDB's own page, saved as `raw/hdb_interest_rate_page.pdf`, establishes the "
      "peg: the concessionary rate is \"pegged at 0.10% above the prevailing CPF "
      "Ordinary Account (OA) interest rate\" and is 2.60 per cent for the two "
      "quarters the page lists.")
    A("")
    A("CPF Board's quarterly interest rate notices for 1 Jan to 31 Mar 2016 "
      "(`raw/cpf2.pdf`) and 1 Jul to 30 Sep 2026 (`raw/cpf3_q3_2026.pdf`) are "
      "primary documents a decade apart. Both state the OA rate held at the 2.5 "
      "per cent legislated floor rather than the lower market-computed rate, and "
      "both state the HDB concessionary rate at 2.6 per cent as the direct, "
      "formula-driven consequence of that floor. cpf2.pdf gives the "
      "market-computed rate the floor overrode as 0.21 per cent.")
    A("")
    A("That closes the window at both ends on primary sources: the peg formula "
      "never changed, and the floor bound at the start of the window and still "
      "bound after its end. No month between the two notices has been checked "
      "individually, so this is not a verified monthly history, only two dated "
      "confirmations that the mechanism producing 2.6 per cent was unchanged "
      "before and after. The verdict is upgraded from PARTIAL to PASS on that "
      "basis, not on a downloaded time series.")
    A("")
    A("Revision note, 16 September 2026: the PARTIAL verdict was hard-coded in "
      "`06_tests.py` before cpf2.pdf and cpf3_q3_2026.pdf, both already "
      "checksummed in raw/, were read against this test. No new data was "
      "downloaded to produce this revision.")
    A("")

    A("## T5 and T6. Composition")
    A("")
    A("| Measure | %d to %d |" % (FIRST, LAST))
    A("|---|---|")
    A("| Hedonic, quadratic lease, pre-registered | %+.1f%% |" % hed_chg)
    if spl is not None:
        spl_chg = 100.0 * (float(spl.loc[LAST, "index"]) / float(spl.loc[FIRST, "index"]) - 1)
        A("| Hedonic, piecewise-linear lease, robustness | %+.1f%% |" % spl_chg)
    A("| Fixed %d basket, Laspeyres | %+.1f%% |" % (FIRST, bas_chg))
    A("| Raw median, uncorrected | %+.1f%% |" % raw_chg)
    A("")
    A("T5: the hedonic and the raw median differ by %.1f points. Threshold for "
      "\"composition mattered\" was 3.0 points, so the verdict is %s. Restricting to "
      "four-room flats had already removed most of the drift before any modelling."
      % (t5_gap, t5))
    A("")
    A("T6: the two correction methods differ by %.1f points, between the 2.0-point "
      "pass and the 5.0-point fail. INCONCLUSIVE as sealed. Both are published and "
      "the article says the correction is doing contested work. F6 is not "
      "triggered, so a single number may be quoted, but never without the other "
      "method beside it." % t6_gap)
    if spl is not None:
        A("")
        A("Robustness: the pre-registered quadratic in remaining lease came back "
          "with a positive second-order term, implying decay slows as the lease "
          "shortens, which is the wrong curvature. Refitting with a piecewise-linear "
          "lease recovers the expected shape and moves the headline by %.1f points, "
          "so the index is insulated from the misspecification."
          % abs(spl_chg - hed_chg))
    A("")

    A("## T7. The median household and the Enhanced CPF Housing Grant ceiling")
    A("")
    A("The EHG ceiling has been 9,000 dollars a month since September 2019. HDB's "
      "own page states it: \"The average gross monthly household income (all "
      "applicants and occupiers) for the months worked during the 12-month period "
      "must not exceed $9,000.\"")
    A("")
    if x is not None:
        A("    I(%d) = %.0f    I(%d) = %.0f    C = %.0f"
          % (det[0], det[1], det[2], det[3], EHG_CEILING))
        A("    crossing = %d + (%.0f - %.0f) / (%.0f - %.0f) = %.1f"
          % (det[0], EHG_CEILING, det[1], det[3], det[1], x))
        A("")
        A("**This is an upper bound on HDB's basis, not a point estimate.** SingStat "
          "includes one-twelfth of the annual bonus and HDB's assessment excludes "
          "bonuses, so the series used here sits above HDB-assessed income. The true "
          "crossing is %.1f or later. See THESIS_ADDENDUM.md entry 2." % x)
        xi, _ = crossing(medi, EHG_CEILING)
        if xi:
            A("")
            A("Sensitivity that vindicates the sealed choice of series: the same "
              "calculation on the INCLUDING-employer-CPF series gives %.1f, a "
              "difference of %.1f years. Using the wrong series would have moved the "
              "answer by more than five years." % (xi, x - xi))
    A("")
    A("| Year | Median income | Share of the 9,000 ceiling |")
    A("|---|---|---|")
    for y in range(FIRST, LAST + 1):
        A("| %d | %.0f | %.1f%% |" % (y, med[y], 100.0 * med[y] / EHG_CEILING))
    A("")
    A("The median household went from %.1f per cent of the ceiling in %d to %.1f "
      "per cent in %d." % (100.0 * med[FIRST] / EHG_CEILING, FIRST,
                           100.0 * med[LAST] / EHG_CEILING, LAST))
    A("")

    A("## T4 premise, checked in the data")
    A("")
    A("The 80th percentile household sits above the EHG ceiling in every one of the "
      "%d window years, and above the purchase and CPF Housing Grant ceiling in "
      "every one as well. It receives no means-tested grant at any point, so the "
      "direction of T4 is a property of the grant schedule rather than a finding. "
      "T4 was reframed to magnitude before the data arrived, in THESIS_ADDENDUM.md "
      "entry 1 of 12 September." % (LAST - FIRST + 1))
    A("")
    A("| Year | 20th percentile | 80th percentile | Above EHG ceiling |")
    A("|---|---|---|---|")
    for y in range(FIRST, LAST + 1):
        A("| %d | %.0f | %.0f | %s |"
          % (y, p20[y], p80[y], "yes" if p80[y] > EHG_CEILING else "NO"))
    A("")

    if t34:
        A("## T3 and T4. Grants, and who they reached")
        A("")
        A("The grant series runs from %d, because the Enhanced CPF Housing Grant "
          "replaced the Additional and Special CPF Housing Grants on 11 September "
          "2019 and the schedule it replaced is not sourced. The Proximity Housing "
          "Grant is omitted by design: it has no income test and is conditional on "
          "living near a parent, so modelling it would mean assuming a living "
          "arrangement." % t34["gy0"])
        A("")
        A("**T3.** For the 20th-percentile buyer, grants rose by %.0f dollars "
          "between %d and %d while the constant-quality price rose by %.0f. The "
          "grant increase covered **%.1f per cent** of the price increase, against "
          "a 40 per cent threshold. T3 FAILS. F3, which would have made grants a "
          "footnote, needed under 10 per cent and is not triggered either. Grants "
          "moved, and moved by too little."
          % (t34["dgrant"], t34["gy0"], t34["gy1"], t34["dprice"],
             100 * t34["share"], ))
        A("")
        A("**T4a FAILS, and in the opposite direction to the one written down.** "
          "The mortgage servicing ratio for the 20th-percentile buyer rose %+.1f "
          "points, the median %+.1f, the 80th percentile %+.1f. The sealed test "
          "predicted the low-income buyer's change would be at least 5 points "
          "SMALLER than the high-income buyer's. It is %.1f points LARGER."
          % (t34["d"]["p20"], t34["d"]["p50"], t34["d"]["p80"], abs(t34["gap"])))
        A("")
        A("Fail condition reached: %s." % t34["t4f"])
        A("")
        A("**T4b FAILS.** The 20th-percentile buyer's ratio is higher at the end "
          "than at the start, so the grant increases did not fully absorb the price "
          "rise for that buyer. Offset is partial at best.")
        A("")
        A("**Why the sealed prediction was wrong, which is the interesting part.** "
          "The loan is the smaller of the loan-to-value cap and the price less "
          "grants. In %d, with the cap at 90 per cent, a large grant bound first "
          "and reduced the loan directly. By %d the cap had been cut to 75 per cent "
          "and it binds instead, so an extra dollar of grant no longer reduces the "
          "loan at all. It goes to the deposit. For the 20th-percentile buyer the "
          "deposit was already fully covered by grants until %d, so the extra grant "
          "did nothing for the monthly repayment. The grant went up and the thing "
          "it was doing stopped."
          % (t34["gy0"], t34["gy1"], t34["gy1"] - 1))
        A("")
        A("A caution the article must carry: comparing percentage-point changes "
          "across buyers whose levels differ this much is not like for like. The "
          "20th-percentile buyer starts at a much higher ratio, so the same "
          "proportional worsening produces a much larger point change. In "
          "proportional terms the ordering is the same but the gap is narrower: "
          "%+.1f per cent, %+.1f per cent and %+.1f per cent for p20, p50 and p80."
          % tuple(100.0 * (t34["msr"][k][t34["gy1"]] / t34["msr"][k][t34["gy0"]] - 1)
                  for k in ("p20", "p50", "p80")))
        A("")
        A("| Year | Grant p20 | Grant p50 | Grant p80 | MSR p20 | MSR p50 | MSR p80 |")
        A("|---|---|---|---|---|---|---|")
        for yy in range(t34["gy0"], t34["gy1"] + 1):
            g = t34["gr"][t34["gr"].year == yy].set_index("buyer")["total_grant"]
            m = t34["aff"][t34["aff"].year == yy].set_index("buyer")["msr_pct"]
            A("| %d | %.0f | %.0f | %.0f | %.1f | %.1f | %.1f |"
              % (yy, g["p20"], g["p50"], g["p80"], m["p20"], m["p50"], m["p80"]))
        A("")
        A("The Enhanced CPF Housing Grant alone, which is the means-tested part: "
          "the median household received 10,000 dollars in %d and nothing from "
          "2023, because its income crossed the 9,000 ceiling. Over the same period "
          "the maximum grant rose from 80,000 to 120,000. The median's TOTAL grant "
          "still rose, from 60,000 to 80,000, because the CPF Housing Grant for "
          "resale went up by 30,000 at Budget 2023 and that one is not tapered. "
          "Both halves of that belong in the article." % t34["gy0"])
        A("")

    A("## Blocked")
    A("")
    if not t34:
        A("T3 and T4 cannot be evaluated. Both need the Enhanced CPF Housing Grant "
          "amount-by-income-band table.")
        A("")
    A("Grants before 11 September 2019: the Additional and Special CPF Housing "
      "Grants are NOT-OBTAINED, so the grant-adjusted measures start in 2019 while "
      "the conventional measure runs from 2013.")
    A("")
    A("The loan-to-value path is sourced for 2021 and 2022 from MOF and MAS "
      "releases, with quotes, in `ltv_schedule.csv`. The August 2024 change to 75 "
      "per cent is still NEEDS-PRIMARY.")
    A("")
    A("Per THESIS.md section 10, if the band table cannot be obtained the "
      "grant-adjusted lead measure is dropped and the article runs on the "
      "conventional measure and the down-payment measure, stating what that omits. "
      "T3 and T4 would then be reported as untestable rather than dropped.")

    text = "\n".join(L) + "\n"
    with open(os.path.join(HERE, "RESULTS.md"), "w", newline="\n") as fh:
        fh.write(text)
    print(text)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print("FAILED: %s" % exc, file=sys.stderr)
        sys.exit(2)
